### ISSUE TITLE
Running on MacOS with Anaconda Python failed

### ISSUE THREAD

**Issue by pancodia** [hao-lee/GraphvizerViewer#1]
### MacOS and Anaconda Python

If you installed Python 3 via Anaconda distribution, then you need to install PySide2 in the conda way. Otherwise, I had similar issue describe in this [SO thread](https://stackoverflow.com/questions/51912816/pyside2-qt-creator-run-issue-could-not-load-the-qt-platform-plugin-cocoa-in/60955108#60955108)

```
conda install -c conda-forge pyside2
python3 GraphvizerViewer.py
```

**Comment by hao-lee** [comment]
Thanks for you contribution! I haven't tried conda before. This is really helpful.
